spring:
  application:
    name: ciams

  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: invuser
    password: inventorydbpsw
    driver-class-name: org.postgresql.Driver

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect


