spring:
  application:
    name: authservice

  data:
    mongodb:
      uri: mongodb://localhost:27017/auth-db

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect



